language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: friend-status-dev
  api_key:
    secure: PPPFNNXzxdHEDusEo0v9qKCu3tdzsuOO51sUg2sq2dk/ZoK51gwMRWJgd3LAd7VuYIjLpHoZibnT2NBrtmKj7/Vfxy9a1u6i3252HscCdGVsMEGh9wNhg4cAQlvHadcCYGhvuqDEq6DeEOaryrF7F5SgZaCebva/tDvYoQ3AWuQNWNzO56nTUYExt0INWGdEC80odkVvXBiG4yktF/vipMEjL0qM9hcAvS3AgBZpmexmo9d8SPRS2mx+qGfXjUVTE2nrp/0F1Z17AXxuopAMal0ZLrzIORBX2Fve/CmIuruxlWWp5Ou8SN9RfhylFb/wck66L2UiukMhRRcuPBBoWggMQz52H1k2GwszklsyjUObbfQBJS1gsFies44BkcYlbT3j85w+dllO1K5pWVn88++wNk5G74u0HQe134Cp7PlRGmY3hD3RUKjn3i6xKOv2DYdttod3MJFVMTGe/JCNhlaYXLe4vR10tykAOSi8TFDOHkhN5lKG+yjthiSk0+BaqAPxdPbzu4mq6jCHknJ5cT1d4Usyojowmp9rmKi3pUIgM4ImzjHAMkv2oIP3j/vyqBBRmVsIqtz03hKhuJgtJOQPR4qwYN322lluSvErKyRD5V5SUZSZj00cPI49gEY6KZZyNwAFr0nZin9DiUVDHNsN51rMBruDtHAXNbYjpp4=