language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: friend-status-dev
  api_key:
    secure: Z5ZEIJViWoidBGaUt1XVLGI8tagsRwBwsSjKOW2UIVd0npe46FNIbDN81MTTUBGHReDiTR+yQX29DI8dKKjvRVV0weqcSi7nIQ5SYhGuopZKi70M7g+GscJGOu5wmo/P2kZn8vHUxRaGRNyAm5G7lvUYMnBGSj5oI0EAaQVrXwya4RDaY1o79cXHXzMyqLcz1vdaoBrYlwNd6+N8RIe+AUOcVVCF+qy3mEuXJjxjBNUFUt4wa5TW7xvVNXzAZD8HpukcLPDWX+KsX96I+B/c8wLg0hrM2kKXcDA4dZETtdGKU6zIGDpvYUivdTUwFfEQX9PJYqA0b8betCKSKiC+g0xgpyJV20euyBNT4doI4/jPMghXVA9jNx9GknU916+tYugUihS8TRuHigWOW30uI+zwRDPV32bR2eTgw4ouN1meRFUO9pqfQC+S5WRsRyKGj6hoapjgl5zG3llX5D8J4LzqCaeIWNa0nveOvl+yd+J/ekeEOwto0QP40DQWV13qpa0U2uGFt6cINqWxWWp3TAwRFiyAYfXBfXVUYRKSgq5RPySxb5cxh5qm3SwhpEW+/PPLMLPioClqZVe4xfPDFv7PdH07xCVlErjC87JvnwJHNAFx7PCn034AP3YMEeNGfIxgPqCCG9264GtJ/lZ8255likrC1XJxgiHLESkzBLE=